TH_ROIS = {
    'PRC', 'MG_v', 'MG_m', 'MG_d', 'POL', 'PP', 'LG_v', 'LG_d', 'IGL', 'PF',
    'SPA', 'SPF_m', 'SPF_p', 'LP', 'VPM', 'VPM_pc', 'PCN', 'CL',
    'VPL', 'VPL_pc', 'SMT', 'VM', 'LD', 'LH', 'MH', 'IMD', 'RT', 'AV', 'AD',
    'AM_d', 'AM_v', 'VAL', 'IAD', 'RE', 'RH', 'IAM', 'CM', 'PT',
    'PVT', 'MD_I', 'MD_m', 'MD_c', 'SGN', 'PO', 'PR', 'SubG'
}

HB_ROIS = {'PAS', 'PARN', 'PRNr', 'PRNc', 'DCO',
      'CNspg', 'ACVII', 'PRP', 'RM', 'RO',
      'GR', 'XII', 'LDT', 'X', 'VII',
      'LAV', 'NLL_h', 'NTS_co', 'DTN', 'PBl_ls', 'PBl_lv', 'NTS_ce',
      'MDRN_v', 'DMX', 'NLL_v', 'PCG', 'PBl_le', 'PBl_ld', 'SPV_i', 'AMB',
      'SPV_c', 'PG', 'VI', 'Y', 'AMB_v', 'TRN',
      'AMB_d', 'GRN', 'CS_m', 'CS_l', 'MV',
      'PSV', 'IP', 'NTS_m', 'NTS_l', 'NTS_ge',
      'SUV', 'SUT', 'ISN', 'MDRN_d', 'SOC_m', 'SOC_l', 'FN', 'NI', 'PBm_m',
      'PGRN_l', 'ECU', 'CNlam', 'PGRN_d', 'NR', 'B',
           'SPIV', 'NLL_d', 'PBm_me', 'V', 'CU', 'SPVO_mdmv', 'KF',
      'MARN', 'SPVO_mdmd', 'SPVO_cdm', 'NTB', 'SG', 'DN', 'SPVO_vl',
      'IRN', 'PONS', 'PBl_lc', 'SPVO_rdm', 'LC',
      'POR', 'RPA', 'PPY',
      'RPO', 'ICB', 'VCO', 'AP', 'IO', 'SLD',
      'SLC', 'LRN_p', 'MY', 'LRN_m'
           }

CTX_COARSE_MAPPING = {
    'MOs_6b': 'MOs', 'ENTm_3': 'ENTm', 'FRP_2/3': 'FRP', 'SSp_tr_1': 'SSp_tr',
    'AON_d': 'AON', 'ENTm_6': 'ENTm', 'ENTm_5': 'ENTm', 'PL_6a': 'PL',
    'PERI_1': 'PERI', 'ILA_6b': 'ILA', 'ILA_6a': 'ILA', 'TTd_3': 'TTd',
    'PERI_5': 'PERI', 'MOp_6b': 'MOp', 'MOp_6a': 'MOp', 'SSp_m_6b': 'SSp_m',
    'MOs_2/3': 'MOs', 'MOs_6a': 'MOs', 'SSp_tr_2/3': 'SSp_tr',
    'SSp_m_6a': 'SSp_m', 'AUDp_2/3': 'AUDp', 'VISam_1': 'VISam',
    'VISl_5': 'VISl', 'VISl_4': 'VISl', 'ECT_2/3': 'ECT', 'AId_5': 'AId',
    'VISl_1': 'VISl', 'AId_1': 'AId', 'SSp_m_4': 'SSp_m', 'SSp_m_5': 'SSp_m',
    'ENTm_4': 'ENTm', 'SSp_m_1': 'SSp_m', 'ENTm_2': 'ENTm',
    'SSp_bfd_5': 'SSp_bfd', 'SSp_bfd_4': 'SSp_bfd', 'SSp_bfd_1': 'SSp_bfd',
    'TEa_6a': 'TEa', 'VISpm_6a': 'VISpm', 'VISpm_6b': 'VISpm', 'TEa_6b': 'TEa',
    'ENTl_2a': 'ENTl', 'PERI_6a': 'PERI', 'PERI_6b': 'PERI', 'ENTl_2b': 'ENTl',
    'VISam_6a': 'VISam', 'VISpl_6b': 'VISpl', 'VISpl_6a': 'VISpl',
    'VISam_6b': 'VISam', 'PAA_2': 'PAA', 'ENTl_4/5': 'ENTl', 'AON_l': 'AON',
    'ACAv_1': 'ACAv', 'TTv_1': 'TTv', 'TTd_4': 'TTd', 'TTd_1': 'TTd',
    'TTd_2': 'TTd', 'SSp_ll_1': 'SSp_ll', 'ACAd_2/3': 'ACAd', 'ACAd_6b': 'ACAd',
    'SSp_n_6b': 'SSp_n', 'MOp_2/3': 'MOp', 'DP_1': 'DP', 'SSp_n_6a': 'SSp_n',
    'PAA_3': 'PAA', 'VISC_6a': 'VISC', 'AUDPo_6a': 'AUDPo', 'AUDv_6b': 'AUDv',
    'SSp_tr_6a': 'SSp_tr', 'VISC_6b': 'VISC', 'SSp_4': 'SSp',
    'SSp_ll_5': 'SSp_ll', 'ORBvl_6b': 'ORBvl', 'AON_pv': 'AON',
    'ORBvl_6a': 'ORBvl', 'ECT_6b': 'ECT', 'ECT_6a': 'ECT', 'AIp_6b': 'AIp',
    'ENTl_6b': 'ENTl', 'PTLp_4': 'PTLp', 'VISp_6b': 'VISp', 'AIv_2/3': 'AIv',
    'AUDv_6a': 'AUDv', 'SSp_m_2/3': 'SSp_m', 'PL_6b': 'PL', 'ACAd_1': 'ACAd',
    'AON_1': 'AON', 'ACAd_5': 'ACAd', 'ACAd_6': 'ACAd', 'AId_2/3': 'AId',
    'ENTm_1': 'ENTm', 'SSp_n_1': 'SSp_n', 'PTLp_6b': 'PTLp', 'SSp_n_5': 'SSp_n',
    'PTLp_6a': 'PTLp', 'ACAv_6a': 'ACAv', 'PIR_2': 'PIR', 'SSp_5': 'SSp',
    'ORBl_2/3': 'ORBl', 'VISl_2/3': 'VISl', 'PL_2/3': 'PL', 'ENTl_2/3': 'ENTl',
    'AUDd_6a': 'AUDd', 'AUDd_6b': 'AUDd', 'AON': 'AON', 'TR_2': 'TR',
    'ORBl_6a': 'ORBl', 'DP_5': 'DP', 'ORBl_6b': 'ORBl', 'RSPv_5': 'RSPv',
    'RSPd_2/3': 'RSPd', 'PTLp_1': 'PTLp', 'AIp_6a': 'AIp', 'MOs_5': 'MOs',
    'PTLp_5': 'PTLp', 'VISp_6a': 'VISp', 'SSp_bfd_6b': 'SSp_bfd',
    'AId_6': 'AId', 'SSp_bfd_6a': 'SSp_bfd', 'AUDpo_6b': 'AUDpo',
    'VISal_2/3': 'VISal', 'ACAv_6b': 'ACAv', 'SSp_ll_6b': 'SSp_ll',
    'SSp_ll_6a': 'SSp_ll', 'DP_2/3': 'DP', 'AON_e': 'AON', 'RSPv_1': 'RSPv',
    'RSPv_2': 'RSPv', 'ILA_3': 'ILA', 'VISC_4': 'VISC', 'VISC_5': 'VISC',
    'NLOT_1': 'NLOT', 'NLOT_2': 'NLOT', 'VISC_1': 'VISC', 'ORBvl_6': 'ORBvl',
    'ORBvl_5': 'ORBvl', 'PAA_1': 'PAA', 'AIp_1': 'AIp', 'ORBvl_1': 'ORBvl',
    'COApm_1': 'COApm', 'AUDPo_2/3': 'AUDPo', 'OT_2': 'OT', 'OT_1': 'OT',
    'COApm_2': 'COApm', 'VISam_5': 'VISam', 'VISC_2/3': 'VISC', 'PIR_1': 'PIR',
    'PIR_3': 'PIR', 'ORBl_6': 'ORBl', 'ACAv_5': 'ACAv', 'ORBm_6': 'ORBm',
    'RSPv_6b': 'RSPv', 'RSPv_6a': 'RSPv', 'ORBm_2': 'ORBm', 'COApm_3': 'COApm',
    'RSPagl_6b': 'RSPagl', 'RSPagl_6a': 'RSPagl', 'ORBm_6a': 'ORBm',
    'ORBm_2/3': 'ORBm', 'GU_2/3': 'GU', 'ECT_1': 'ECT', 'SSp_6a': 'SSp',
    'ECT_5': 'ECT', 'RSPv_2/3': 'RSPv', 'SSp_6b': 'SSp', 'VISpm_2/3': 'VISpm',
    'VISam_4': 'VISam', 'AUDp_6a': 'AUDp', 'ENTl_6a': 'ENTl',
    'ENTmv_1': 'ENTmv', 'ENTmv_2': 'ENTmv', 'ENTmv_3': 'ENTmv', 'AIv_6b': 'AIv',
    'AIv_6a': 'AIv', 'PL_5': 'PL', 'AUDv_2/3': 'AUDv', 'AUDp_6b': 'AUDp',
    'PL_6': 'PL', 'PL_1': 'PL', 'PL_3': 'PL', 'PL_2': 'PL', 'FRP_1': 'FRP',
    'TEa_2/3': 'TEa', 'SSp-un_2/3': 'SSp-un', 'SSp_ul_1': 'SSp_ul',
    'RSPd_1': 'RSPd', 'SSp_ul_5': 'SSp_ul', 'SSp_ul_4': 'SSp_ul',
    'ACAd_6a': 'ACAd', 'SSp_ul_6b': 'SSp_ul', 'COApl_1': 'COApl',
    'COApl_2': 'COApl', 'SSp_ul_6a': 'SSp_ul', 'ACAv_2/3': 'ACAv',
    'SSp_ll_2/3': 'SSp_ll', 'SSp-un_4': 'SSp-un', 'Ep_v': 'Ep_v',
    'AId_6b': 'AId', 'AUDp_5': 'AUDp', 'AUDp_4': 'AUDp', 'AIp_5': 'AIp',
    'AUDp_1': 'AUDp', 'ILA_2/3': 'ILA', 'MOp_6': 'MOp', 'AUDv_5': 'AUDv',
    'AUDv_4': 'AUDv', 'AIp_2/3': 'AIp', 'ENTm_2a': 'ENTm', 'AUDv_1': 'AUDv',
    'VISpm_1': 'VISpm', 'EP_d': 'EP_d', 'VISpl_2/3': 'VISpl', 'ORBl_1': 'ORBl',
    'VISpm_5': 'VISpm', 'VISpm_4': 'VISpm', 'ORBl_5': 'ORBl', 'RSPd_6a': 'RSPd',
    'RSPd_6b': 'RSPd', 'SSs_2/3': 'SSs', 'SSs_6a': 'SSs', 'SSs_6b': 'SSs',
    'COAa_1': 'COAa', 'AUDd_1': 'AUDd', 'AIv_1': 'AIv', 'SSp_1': 'SSp',
    'AUDd_5': 'AUDd', 'AUDd_4': 'AUDd', 'SSp_tr_6b': 'SSp_tr', 'TR_3': 'TR',
    'ILA_5': 'ILA', 'TR_1': 'TR', 'SSp_n_4': 'SSp_n', 'ENTmv_5/6': 'ENTmv',
    'SSp_ul_2/3': 'SSp_ul', 'ILA_2': 'ILA', 'RSPd_5': 'RSPd',
    'SSp-un_6b': 'SSp-un', 'ENTl_2': 'ENTl', 'RSPagl_2/3': 'RSPagl',
    'SSp-un_6a': 'SSp-un', 'ENTl_3': 'ENTl', 'AIv_5': 'AIv',
    'ORBvl_2/3': 'ORBvl', 'COApl_3': 'COApl', 'AUDd_2/3': 'AUDd',
    'ENTl_6': 'ENTl', 'ENTl_4': 'ENTl', 'ENTl_5': 'ENTl', 'DP_6a': 'DP',
    'MOs_6': 'MOs', 'ENTl_1': 'ENTl', 'GU_6a': 'GU', 'GU_6b': 'GU',
    'NLOT_3': 'NLOT', 'GU_1': 'GU', 'SSp_bfd_2/3': 'SSp_bfd',
    'VISp_2/3': 'VISp', 'GU_5': 'GU', 'GU_4': 'GU', 'SSp_tr_4': 'SSp_tr',
    'SSp_tr_5': 'SSp_tr', 'ENTm_2b': 'ENTm', 'COAa_2': 'COAa', 'TEa_4': 'TEa',
    'TEa_5': 'TEa', 'TEa_1': 'TEa', 'VISp_5': 'VISp', 'VISal_1': 'VISal',
    'SSp_ll_4': 'SSp_ll', 'SSp_n_2/3': 'SSp_n', 'VISal_5': 'VISal',
    'VISal_4': 'VISal', 'AON_m': 'AON', 'VISal_6b': 'VISal',
    'VISal_6a': 'VISal', 'AId_6a': 'AId', 'VISl_6a': 'VISl', 'VISl_6b': 'VISl',
    'SSp_2/3': 'SSp', 'PTLp_2/3': 'PTLp', 'MOs_1': 'MOs', 'CLA': 'CLA',
    'RSPagl_1': 'RSPagl', 'SSs_5': 'SSs', 'SSs_4': 'SSs', 'AUDPo_1': 'AUDPo',
    'SSs_1': 'SSs', 'AUDPo_5': 'AUDPo', 'AUDPo_4': 'AUDPo', 'MOp_1': 'MOp',
    'SSp-un_5': 'SSp-un', 'PERI_2/3': 'PERI', 'MOp_5': 'MOp',
    'SSp-un_1': 'SSp-un', 'ILA_1': 'ILA', 'RSPagl_5': 'RSPagl',
    'VISp_1': 'VISp', 'TTv_2': 'TTv', 'VISam_2/3': 'VISam', 'VISp_4': 'VISp',
    'TTv_3': 'TTv', 'ORBm_3': 'ORBm', 'VISpl_1': 'VISpl', 'ORBm_1': 'ORBm',
    'OT_3': 'OT', 'VISpl_4': 'VISpl', 'VISpl_5': 'VISpl', 'ORBm_5': 'ORBm',
    'MOB_opl': 'MOB', 'MOB_mi': 'MOB', 'MOB_gr': 'MOB', 'MOB_ipl': 'MOB', 'MOB_gl': 'MOB', 'MOB': 'MOB'
}

CTX_DS_MAPPING = {
    'MOs_6b': 'MOs_d', 'ENTm_3': 'ENTm_s', 'FRP_2/3': 'FRP_s',
    'SSp_tr_1': 'SSp_tr_s', 'AON_d': 'AON_d', 'ENTm_6': 'ENTm_d',
    'ENTm_5': 'ENTm_d', 'PL_6a': 'PL_d', 'PERI_1': 'PERI_s', 'ILA_6b': 'ILA_d',
    'ILA_6a': 'ILA_d', 'TTd_3': 'Ttd_d', 'PERI_5': 'PERI_d', 'MOp_6b': 'MOp_d',
    'MOp_6a': 'MOp_d', 'SSp_m_6b': 'SSp_m_d', 'MOs_2/3': 'MOs_s',
    'MOs_6a': 'MOs_d', 'SSp_tr_2/3': 'SSp_tr_s', 'SSp_m_6a': 'SSp_m_d',
    'AUDp_2/3': 'AUDp_s', 'VISam_1': 'VISam_s', 'VISl_5': 'VISl_d',
    'VISl_4': 'VISl_d', 'ECT_2/3': 'ECT_s', 'AId_5': 'AId_d',
    'VISl_1': 'VISl_s', 'AId_1': 'AId_s', 'SSp_m_4': 'SSp_m_d',
    'SSp_m_5': 'SSp_m_d', 'ENTm_4': 'ENTm_d', 'SSp_m_1': 'SSp_m_s',
    'ENTm_2': 'ENTm_s', 'SSp_bfd_5': 'SSp_bfd_d', 'SSp_bfd_4': 'SSp_bfd_d',
    'SSp_bfd_1': 'SSp_bfd_s', 'TEa_6a': 'TEa_d', 'VISpm_6a': 'VISpm_d',
    'VISpm_6b': 'VISpm_d', 'TEa_6b': 'TEa_d', 'ENTl_2a': 'ENTl_s',
    'PERI_6a': 'PERI_d', 'PERI_6b': 'PERI_d', 'ENTl_2b': 'ENTl_s',
    'VISam_6a': 'VISam_d', 'VISpl_6b': 'VISpl_d', 'VISpl_6a': 'VISpl_d',
    'VISam_6b': 'VISam_d', 'PAA_2': 'PAA_s', 'ENTl_4/5': 'ENTl_d',
    'AON_l': 'AON_l', 'ACAv_1': 'ACAv_s', 'TTv_1': 'TTv_s', 'TTd_4': 'TTd_d',
    'TTd_1': 'TTd_s', 'TTd_2': 'TTd_s', 'SSp_ll_1': 'SSp_ll_s',
    'ACAd_2/3': 'ACAd_s', 'ACAd_6b': 'ACAd_d', 'SSp_n_6b': 'SSp_n_d',
    'MOp_2/3': 'MOp_s', 'DP_1': 'DP_s', 'SSp_n_6a': 'SSp_n_d', 'PAA_3': 'PAA_d',
    'VISC_6a': 'VISC_d', 'AUDPo_6a': 'AUDPo_d', 'AUDv_6b': 'AUDv_d',
    'SSp_tr_6a': 'SSp_tr_d', 'VISC_6b': 'VISC_d', 'SSp_4': 'SSp_d',
    'SSp_ll_5': 'SSp_ll_d', 'ORBvl_6b': 'ORBvl_d', 'AON_pv': 'AON_pv',
    'ORBvl_6a': 'ORBvl_d', 'ECT_6b': 'ECT_d', 'ECT_6a': 'ECT_d',
    'AIp_6b': 'AIp_d', 'ENTl_6b': 'ENTl_d', 'PTLp_4': 'PTLp_d',
    'VISp_6b': 'VISp_d', 'AIv_2/3': 'AIv_s', 'AUDv_6a': 'AUDv_d',
    'SSp_m_2/3': 'SSp_m_s', 'PL_6b': 'PL_d', 'ACAd_1': 'ACAd_s',
    'AON_1': 'AON', 'ACAd_5': 'ACAd_d', 'ACAd_6': 'ACAd_d', 'AId_2/3': 'AId_s',
    'ENTm_1': 'ENTm_s', 'SSp_n_1': 'SSp_n_s', 'PTLp_6b': 'PTLp_d',
    'SSp_n_5': 'SSp_n_d', 'PTLp_6a': 'PTLp_d', 'ACAv_6a': 'ACAv_d',
    'PIR_2': 'PIR_s', 'SSp_5': 'SSp_d', 'ORBl_2/3': 'ORBl_s',
    'VISl_2/3': 'VISl_s', 'PL_2/3': 'PL_s', 'ENTl_2/3': 'ENTl_s',
    'AUDd_6a': 'AUDd_d', 'AUDd_6b': 'AUDd_d', 'AON': 'AON', 'TR_2': 'TR_s',
    'ORBl_6a': 'ORBl_d', 'DP_5': 'DP_d', 'ORBl_6b': 'ORBl_d',
    'RSPv_5': 'RSPv_d', 'RSPd_2/3': 'RSPd_s', 'PTLp_1': 'PTLp_s',
    'AIp_6a': 'AIp_d', 'MOs_5': 'MOs_d', 'PTLp_5': 'PTLp_d',
    'VISp_6a': 'VISp_d', 'SSp_bfd_6b': 'SSp_bfd_d', 'AId_6': 'AId_d',
    'SSp_bfd_6a': 'SSp_bfd_d', 'AUDpo_6b': 'AUDpo_d', 'VISal_2/3': 'VISal_s',
    'ACAv_6b': 'ACAv_d', 'SSp_ll_6b': 'SSp_ll_d', 'SSp_ll_6a': 'SSp_ll_d',
    'DP_2/3': 'DP_s', 'AON_e': 'AON_e', 'RSPv_1': 'RSPv_s', 'RSPv_2': 'RSPv_s',
    'ILA_3': 'ILA_s', 'VISC_4': 'VISC_d', 'VISC_5': 'VISC_d',
    'NLOT_1': 'NLOT_s', 'NLOT_2': 'NLOT_s', 'VISC_1': 'VISC_s',
    'ORBvl_6': 'ORBvl_d', 'ORBvl_5': 'ORBvl_d', 'PAA_1': 'PAA_s',
    'AIp_1': 'AIp_s', 'ORBvl_1': 'ORBvl_s', 'COApm_1': 'COApm_s',
    'AUDPo_2/3': 'AUDPo_s', 'OT_2': 'OT_s', 'OT_1': 'OT_s',
    'COApm_2': 'COApm_s', 'VISam_5': 'VISam_d', 'VISC_2/3': 'VISC_s',
    'PIR_1': 'PIR_s', 'PIR_3': 'PIR_d', 'ORBl_6': 'ORBl_d', 'ACAv_5': 'ACAv_d',
    'ORBm_6': 'ORBm_d', 'RSPv_6b': 'RSPv_d', 'RSPv_6a': 'RSPv_d',
    'ORBm_2': 'ORBm_s', 'COApm_3': 'COApm_d', 'RSPagl_6b': 'RSPagl_d',
    'RSPagl_6a': 'RSPagl_d', 'ORBm_6a': 'ORBm_d', 'ORBm_2/3': 'ORBm_s',
    'GU_2/3': 'GU_s', 'ECT_1': 'ECT_s', 'SSp_6a': 'SSp_d', 'ECT_5': 'ECT_d',
    'RSPv_2/3': 'RSPv_s', 'SSp_6b': 'SSp_d', 'VISpm_2/3': 'VISpm_s',
    'VISam_4': 'VISam_d', 'AUDp_6a': 'AUDp_d', 'ENTl_6a': 'ENTl_d',
    'ENTmv_1': 'ENTmv_s', 'ENTmv_2': 'ENTmv_s', 'ENTmv_3': 'ENTmv_s',
    'AIv_6b': 'AIv_d', 'AIv_6a': 'AIv_d', 'PL_5': 'PL_d', 'AUDv_2/3': 'AUDv_s',
    'AUDp_6b': 'AUDp_d', 'PL_6': 'PL_d', 'PL_1': 'PL_s', 'PL_3': 'PL_s',
    'PL_2': 'PL_s', 'FRP_1': 'FRP_s', 'TEa_2/3': 'TEa_s',
    'SSp-un_2/3': 'SSp-un_s', 'SSp_ul_1': 'SSp_ul_s', 'RSPd_1': 'RSPd_s',
    'SSp_ul_5': 'SSp_ul_d', 'SSp_ul_4': 'SSp_ul_d', 'ACAd_6a': 'ACAd_d',
    'SSp_ul_6b': 'SSp_ul_d', 'COApl_1': 'COApl_s', 'COApl_2': 'COApl_s',
    'SSp_ul_6a': 'SSp_ul_d', 'ACAv_2/3': 'ACAv_s', 'SSp_ll_2/3': 'SSp_ll_s',
    'SSp-un_4': 'SSp-un_d', 'Ep_v': 'EP_v', 'AId_6b': 'AId_d', 'AUDp_5': 'AUDp_d',
    'AUDp_4': 'AUDp_d', 'AIp_5': 'AIp_d', 'AUDp_1': 'AUDp_s',
    'ILA_2/3': 'ILA_s', 'MOp_6': 'MOp_d', 'AUDv_5': 'AUDv_d',
    'AUDv_4': 'AUDv_d', 'AIp_2/3': 'AIp_s', 'ENTm_2a': 'ENTm_s',
    'AUDv_1': 'AUDv_s', 'VISpm_1': 'VISpm_s', 'EP_d': 'EP_d',
    'VISpl_2/3': 'VISpl_s', 'ORBl_1': 'ORBl_s', 'VISpm_5': 'VISpm_d',
    'VISpm_4': 'VISpm_d', 'ORBl_5': 'ORBl_d', 'RSPd_6a': 'RSPd_d',
    'RSPd_6b': 'RSPd_d', 'SSs_2/3': 'SSs_s', 'SSs_6a': 'SSs_d',
    'SSs_6b': 'SSs_d', 'COAa_1': 'COAa_s', 'AUDd_1': 'AUDd_s', 'AIv_1': 'AIv_s',
    'SSp_1': 'SSp_s', 'AUDd_5': 'AUDd_d', 'AUDd_4': 'AUDd_d',
    'SSp_tr_6b': 'SSp_tr_d', 'TR_3': 'TR_d', 'ILA_5': 'ILA_d', 'TR_1': 'TR_s',
    'SSp_n_4': 'SSp_n_d', 'ENTmv_5/6': 'ENTmv_d', 'SSp_ul_2/3': 'SSp_ul_s',
    'ILA_2': 'ILA_s', 'RSPd_5': 'RSPd_d', 'SSp-un_6b': 'SSp-un_d',
    'ENTl_2': 'ENTl_s', 'RSPagl_2/3': 'RSPagl_s', 'SSp-un_6a': 'SSp-un_d',
    'ENTl_3': 'ENTl_s', 'AIv_5': 'AIv_d', 'ORBvl_2/3': 'ORBvl_s',
    'COApl_3': 'COApl_d', 'AUDd_2/3': 'AUDd_s', 'ENTl_6': 'ENTl_d',
    'ENTl_4': 'ENTl_d', 'ENTl_5': 'ENTl_d', 'DP_6a': 'DP_d', 'MOs_6': 'MOs_d',
    'ENTl_1': 'ENTl_s', 'GU_6a': 'GU_d', 'GU_6b': 'GU_d', 'NLOT_3': 'NLOT_d',
    'GU_1': 'GU_s', 'SSp_bfd_2/3': 'SSp_bfd_s', 'VISp_2/3': 'VISp_s',
    'GU_5': 'GU_d', 'GU_4': 'GU_d', 'SSp_tr_4': 'SSp_tr_d',
    'SSp_tr_5': 'SSp_tr_d', 'ENTm_2b': 'ENTm_s', 'COAa_2': 'COAa_s',
    'TEa_4': 'TEa_d', 'TEa_5': 'TEa_d', 'TEa_1': 'TEa_s', 'VISp_5': 'VISp_d',
    'VISal_1': 'VISal_s', 'SSp_ll_4': 'SSp_ll_d', 'SSp_n_2/3': 'SSp_n_s',
    'VISal_5': 'VISal_d', 'VISal_4': 'VISal_d', 'AON_m': 'AON_m',
    'VISal_6b': 'VISal_d', 'VISal_6a': 'VISal_d', 'AId_6a': 'AId_d',
    'VISl_6a': 'VISl_d', 'VISl_6b': 'VISl_d', 'SSp_2/3': 'SSp_s',
    'PTLp_2/3': 'PTLp_s', 'MOs_1': 'MOs_s', 'CLA': 'CLA',
    'RSPagl_1': 'RSPagl_s', 'SSs_5': 'SSs_d', 'SSs_4': 'SSs_d',
    'AUDPo_1': 'AUDPo_s', 'SSs_1': 'SSs_s', 'AUDPo_5': 'AUDPo_d',
    'AUDPo_4': 'AUDPo_d', 'MOp_1': 'MOp_s', 'SSp-un_5': 'SSp-un_d',
    'PERI_2/3': 'PERI_s', 'MOp_5': 'MOp_d', 'SSp-un_1': 'SSp-un_s',
    'ILA_1': 'ILA_s', 'RSPagl_5': 'RSPagl_d', 'VISp_1': 'VISp_s',
    'TTv_2': 'TTv_s', 'VISam_2/3': 'VISam_s', 'VISp_4': 'VISp_d',
    'TTv_3': 'Ttv_d', 'ORBm_3': 'ORBm_s', 'VISpl_1': 'VISpl_s',
    'ORBm_1': 'ORBm_s', 'OT_3': 'OT_d', 'VISpl_4': 'VISpl_d',
    'VISpl_5': 'VISpl_d', 'ORBm_5': 'ORBm_d',
    'MOB_opl': 'MOB_s', 'MOB_mi': 'MOB_d', 'MOB_gr': 'MOB_d', 'MOB_ipl': 'MOB_d', 'MOB_gl': 'MOB_s', 'MOB': 'MOB_d'
}

OLFACTORY_AREA_COARSE_MAPPING = {
    'COApm_1': 'COApm', 'COApm_2': 'COApm', 'COApm_3': 'COApm', 'TTd_2': 'TTd', 'TR_3': 'TR', 'TR_2': 'TR',
    'AOB_gl': 'AOB', 'TTd_3': 'TTd', 'AOB_mi': 'AOB', 'TTv_2': 'TTv', 'AOB_gr': 'AOB', 'AON_1': 'AON',
    'COApl_1': 'COApl', 'COApl_3': 'COApl', 'COApl_2': 'COApl', 'TTv_3': 'TTv', 'DP_6a': 'DP', 'AOB': 'AOB',
    'MOB_opl': 'MOB', 'PIR_1': 'PIR', 'AON': 'AON', 'PIR_3': 'PIR', 'PIR_2': 'PIR', 'COAa_2': 'COAa', 'COAa_1': 'COAa',
    'TR_1': 'TR', 'AON_d': 'AON', 'AON_e': 'AON', 'TRN': 'TRN', 'AON_pv': 'AON', 'AON_l': 'AON', 'AON_m': 'AON',
    'PAA_2': 'PAA', 'PAA_3': 'PAA', 'TTd_1': 'TTd', 'PAA_1': 'PAA', 'DP_5': 'DP', 'DP_1': 'DP', 'MOB_mi': 'MOB',
    'NLOT_2': 'NLOT', 'NLOT_3': 'NLOT', 'TRS': 'TRS', 'TTd_4': 'TTd', 'MOB_gr': 'MOB', 'TTv_1': 'TTv',
    'MOB_ipl': 'MOB', 'MOB_gl': 'MOB', 'DP_2/3': 'DP', 'MOB': 'MOB', 'NLOT_1': 'NLOT'
}

SENSORY_AREA_COARSE_MAPPING = {
    'SSp_tr_1': 'SSp_tr', 'AOB_gl': 'AOB', 'SSp_m_6b': 'SSp_m', 'SSp_tr_2/3': 'SSp_tr', 'SSp_m_6a': 'SSp_m',
    'AUDp_2/3': 'AUDp', 'VISl_5': 'VISl', 'VISl_4': 'VISl', 'AON_e': 'AON', 'VISl_1': 'VISl', 'AOB': 'AOB',
    'SSp_m_4': 'SSp_m', 'SSp_m_5': 'SSp_m', 'SSp_m_1': 'SSp_m', 'SSp_bfd_5': 'SSp_bfd', 'SSp_bfd_4': 'SSp_bfd',
    'SSp_bfd_1': 'SSp_bfd', 'VISpm_6a': 'VISpm', 'VISpm_6b': 'VISpm', 'VISam_6a': 'VISam', 'VISpl_6b': 'VISpl',
    'VISpl_6a': 'VISpl', 'VISam_6b': 'VISam', 'AON_l': 'AON', 'AON_m': 'AON', 'TTd_4': 'TTd', 'MOB_gl': 'MOB',
    'TTd_1': 'TTd', 'TTd_2': 'TTd', 'TTd_3': 'TTd', 'SSp_n_6b': 'SSp_n', 'SSp_n_6a': 'SSp_n', 'VISC_6a': 'VISC',
    'VISC_6b': 'VISC', 'AUDv_6b': 'AUDv', 'AUDv_6a': 'AUDv', 'SSp_4': 'SSp', 'SSp_n_2/3': 'SSp_n', 'MOB_gr': 'MOB',
    'VISp_6a': 'VISp', 'VISp_6b': 'VISp', 'AOB_gr': 'AOB', 'SSp_1': 'SSp', 'SSp_m_2/3': 'SSp_m', 'AON_1': 'AON',
    'AOB_mi': 'AOB', 'SSp_n_1': 'SSp_n', 'SSp_n_5': 'SSp_n', 'SSs_2/3': 'SSs', 'GU_6a': 'GU', 'SSp_5': 'SSp',
    'VISl_2/3': 'VISl', 'AUDd_6a': 'AUDd', 'AUDd_6b': 'AUDd', 'AON_pv': 'AON', 'SSp_bfd_6b': 'SSp_bfd',
    'SSp_bfd_6a': 'SSp_bfd', 'AUDpo_6b': 'AUDpo', 'VISal_2/3': 'VISal', 'TRN': 'TRN', 'SSp_ll_6b': 'SSp_ll',
    'SSp_ll_6a': 'SSp_ll', 'PAA_2': 'PAA', 'PAA_3': 'PAA', 'PAA_1': 'PAA', 'VISC_4': 'VISC', 'VISpm_2/3': 'VISpm',
    'MOB_mi': 'MOB', 'NLOT_2': 'NLOT', 'VISC_1': 'VISC', 'TRS': 'TRS', 'AUDPo_2/3': 'AUDPo', 'VISC_2/3': 'VISC',
    'VISC_5': 'VISC', 'AON': 'AON', 'MOB': 'MOB', 'AUDp_6a': 'AUDp', 'NLOT_1': 'NLOT', 'COApm_1': 'COApm',
    'COApm_2': 'COApm', 'COApm_3': 'COApm', 'NLOT_3': 'NLOT', 'GU_2/3': 'GU', 'SSp_tr_6a': 'SSp_tr', 'SSp_6a': 'SSp',
    'SSp_6b': 'SSp', 'VISam_1': 'VISam', 'VISam_4': 'VISam', 'VISam_5': 'VISam', 'PIR_1': 'PIR', 'PIR_3': 'PIR',
    'PIR_2': 'PIR', 'AUDv_2/3': 'AUDv', 'AUDp_6b': 'AUDp', 'SSp-un_2/3': 'SSp-un', 'SSp_ul_1': 'SSp_ul',
    'SSp_ul_5': 'SSp_ul', 'SSp_ul_4': 'SSp_ul', 'SSp_ul_6b': 'SSp_ul', 'SSp_ul_6a': 'SSp_ul', 'DP_5': 'DP',
    'SSp_ll_2/3': 'SSp_ll', 'DP_1': 'DP', 'AUDp_5': 'AUDp', 'AUDp_4': 'AUDp', 'AUDp_1': 'AUDp', 'AUDv_5': 'AUDv',
    'AUDv_4': 'AUDv', 'TTv_1': 'TTv', 'AUDv_1': 'AUDv', 'VISpm_1': 'VISpm', 'MOB_ipl': 'MOB', 'VISpl_2/3': 'VISpl',
    'VISpm_5': 'VISpm', 'VISpm_4': 'VISpm', 'DP_2/3': 'DP', 'SSs_6a': 'SSs', 'SSs_6b': 'SSs', 'AUDd_1': 'AUDd',
    'AUDd_5': 'AUDd', 'AUDd_4': 'AUDd', 'SSp_tr_6b': 'SSp_tr', 'TR_3': 'TR', 'TR_2': 'TR', 'TR_1': 'TR',
    'SSp_n_4': 'SSp_n', 'AON_d': 'AON', 'SSp-un_6b': 'SSp-un', 'SSp-un_6a': 'SSp-un', 'COApl_1': 'COApl',
    'COApl_3': 'COApl', 'AUDd_2/3': 'AUDd', 'VISam_2/3': 'VISam', 'DP_6a': 'DP', 'COApl_2': 'COApl',
    'SSp_ul_2/3': 'SSp_ul', 'GU_6b': 'GU', 'MOB_opl': 'MOB', 'GU_1': 'GU', 'SSp_bfd_2/3': 'SSp_bfd',
    'VISp_2/3': 'VISp', 'GU_5': 'GU', 'GU_4': 'GU', 'SSp_tr_4': 'SSp_tr', 'SSp_tr_5': 'SSp_tr', 'COAa_2': 'COAa',
    'COAa_1': 'COAa', 'SSp_ll_1': 'SSp_ll', 'VISal_1': 'VISal', 'SSp_ll_4': 'SSp_ll', 'SSp_ll_5': 'SSp_ll',
    'VISal_5': 'VISal', 'VISal_4': 'VISal', 'VISal_6b': 'VISal', 'VISal_6a': 'VISal', 'VISl_6a': 'VISl',
    'VISl_6b': 'VISl', 'AUDPo_6a': 'AUDPo', 'SSp_2/3': 'SSp', 'SSs_5': 'SSs', 'SSs_4': 'SSs', 'AUDPo_1': 'AUDPo',
    'SSs_1': 'SSs', 'AUDPo_5': 'AUDPo', 'AUDPo_4': 'AUDPo', 'SSp-un_5': 'SSp-un', 'SSp-un_4': 'SSp-un',
    'SSp-un_1': 'SSp-un', 'VISp_1': 'VISp', 'TTv_2': 'TTv', 'VISp_5': 'VISp', 'VISp_4': 'VISp', 'TTv_3': 'TTv',
    'VISpl_1': 'VISpl', 'VISpl_4': 'VISpl', 'VISpl_5': 'VISpl'}


AMY_COARSE_MAPPING = {
    'BLA_a': 'BLA', 'BLA_v': 'BLA', 'AAA': 'AAA', 'CEA_c': 'CEA',
    'BLA_p': 'BLA', 'BMA_p': 'BMA_p', 'LA': 'LA', 'BA': 'BA', 'MEA_av': 'MEA',
    'IA': 'IA', 'sAMY': 'sAMY', 'PA': 'PA', 'MEA_pd_c': 'MEA',
    'MEA_pd_b': 'MEA', 'MEA_pd_a': 'MEA', 'BMA_a': 'BMA_a', 'CEA_m': 'CEA',
    'CEA_l': 'CEA', 'MEA_pv': 'MEA', 'MEA_ad': 'MEA'
}

AMY_COA_ROIS = {
    'BLA_a', 'BLA_p', 'BLA_v', 'LA', 'BMA_a', 'BMA_p', 'PA', 'COAa_1',
    'COAa_2', 'COApl_1', 'COApl_2', 'COApl_3', 'COApm_1', 'COApm_2',
    'COApm_3', 'AAA', 'IA', 'MEA_pd_a', 'MEA_pd_b', 'MEA_pd_c', 'MEA_ad',
    'MEA_av', 'MEA_pv', 'BA', 'CEA_m', 'CEA_l', 'CEA_c', 'PAA_1', 'PAA_2',
    'PAA_3'
}

HY_COARSE_MAPPING = {
    'HY': 'HY', 'TU': 'TU', 'PVR_pd': 'PVR_pd', 'PM_v': 'PM', 'ZI_FF': 'ZI',
    'PV_po': 'PV', 'AHN_c': 'AHN', 'PVH_mm': 'PVH', 'AHN_a': 'AHN',
    'AHN_p': 'AHN', 'RCH': 'RCH', 'PM_d': 'PM', 'PVH_pv': 'PVH', 'LM': 'LM',
    'ADP': 'ADP', 'PVH_ap': 'PVH', 'PS': 'PS', 'PV_a': 'PV', 'SCH': 'SCH',
    'A13': 'A13', 'ZI_A13': 'ZI', 'MEPO': 'MEPO', 'PV_i': 'PV', 'NC': 'NC',
    'SBPV': 'SBPV', 'PV_p': 'PV', 'VMH_dm': 'VMH', 'SO': 'SO', 'PH': 'PH',
    'AVPV': 'AVPV', 'MM_me': 'MM_me', 'TM_d': 'TM', 'ZI': 'ZI', 'LHA': 'LHA',
    'DMH_v': 'DMH', 'STN': 'STN', 'PVH_lp': 'PVH', 'DMH_p': 'DMH', 'LPO': 'LPO',
    'PVH_dp': 'PVH', 'TM_v': 'TM', 'SFO': 'SFO', 'VMH_vl': 'VMH',
    'DMH_a': 'DMH', 'VLPO': 'VLPO', 'ME': 'ME', 'SUM_m': 'SUM', 'SUM_l': 'SUM',
    'PVH_pmm': 'PVH', 'PVH_pml': 'PVH', 'MM': 'MM', 'MPO': 'MPO', 'AVP': 'AVP',
    'ADH_p': 'ADH_p', 'PSTN': 'PSTN', 'PVH_mpv': 'PVH', 'PVH_f': 'PVH',
    'MPN': 'MPN', 'MPN_m': 'MPN', 'MPN_l': 'MPN', 'VMH_a': 'VMH',
    'VMH_c': 'VMH', 'PVH_a': 'PVH', 'ARH': 'ARH', 'OV': 'OV', 'MPN_c': 'MPN',
    'PVH_mpd': 'PVH', 'PST': 'PST'
}

STR_COARSE_MAPPING = {
    'ACB': 'ACB', 'FS': 'FS', 'BST_mg': 'BST', 'Gpi': 'Gpi', 'Gpe': 'Gpe',
    'BST_pr': 'BST', 'LS_r': 'LS_r', 'BST_rh': 'BST', 'BST_AM': 'BST',
    'BST_BAC': 'BST', 'BST_AL': 'BST', 'BST_v': 'BST', 'BST_OV': 'BST',
    'BST_if': 'BST', 'BST_d': 'BST', 'BST_fu': 'BST', 'LS_c': 'LS_c',
    'NDB': 'NDB', 'BST_dm': 'BST', 'BST_se': 'BST', 'TRS': 'TRS', 'CP': 'CP',
    'LS_v': 'LS_v', 'BST_ju': 'BST', 'MA': 'MA', 'SI': 'SI', 'MS': 'MS',
    'SF': 'SF', 'BST_tr': 'BST', 'SH': 'SH'
}

HPF_COARSE_MAPPING = {
    'CA3_sp': 'CA3', 'CA3_sr': 'CA3', 'CA3_so': 'CA3', 'FC': 'FC',
    'SUBd_m': 'SUB_d', 'DG_mo': 'DG', 'DG_po': 'DG', 'POST_1': 'POST',
    'POST_3': 'POST', 'POST_2': 'POST', 'CA2_sr': 'CA2', 'CA2_sp': 'CA2',
    'SUBv_sp': 'SUB_v', 'SUBv_sr': 'SUB_v', 'CA1_slm': 'CA1', 'PRE_3': 'PRE',
    'PRE_2': 'PRE', 'PRE_1': 'PRE', 'SUBd_sr': 'SUB_d', 'CA2_so': 'CA2',
    'IG': 'IG', 'PAR_1': 'PAR', 'PAR_3': 'PAR', 'PAR_2': 'PAR', 'CA1_sr': 'CA1',
    'CA1_sp': 'CA1', 'CA3_slm': 'CA3', 'SUBv_m': 'SUB_v', 'CA1_so': 'CA1',
    'CA3_slu': 'CA3', 'DG_sg': 'DG', 'SUBd_sp': 'SUB_d', 'CA2_slm': 'CA2'
}

MB_COARSE_MAPPING = {
    'SCm_dw': 'SCm', 'SN_c': 'SN_c', 'PAG': 'PAG', 'SCs_zo': 'SCs',
    'SCs_op': 'SCs', 'SCM_ig-a': 'SCm', 'SCM_ig-c': 'SCm', 'SCM_ig-b': 'SCm',
    'SN_r': 'SN_r', 'DR': 'DR', 'Scig_b': 'Scig_b', 'SCs_sg': 'SCs',
    'IC_c': 'IC_c', 'IC_e': 'IC_e', 'IC_d': 'IC_d', 'RR': 'RR', 'NB': 'NB',
    'SAG': 'SAG', 'PPN': 'PPN', 'SCm_iw': 'SCm', 'LT': 'LT', 'PPT': 'PPT',
    'RL': 'RL', 'RN': 'RN', 'III': 'III', 'VTA': 'VTA', 'SCm_ig': 'SCm',
    'CLI': 'CLI', 'VTN': 'VTN', 'PBG': 'PBG', 'AT': 'AT', 'CUN': 'CUN',
    'EW': 'EW', 'IV': 'IV', 'IF': 'IF', 'SCm_dg': 'SCm', 'MB': 'MB',
    'IPN': 'IPN', 'MRN': 'MRN', 'NPC': 'NPC', 'MPT': 'MPT', 'MEV': 'MEV',
    'APN': 'APN', 'NOT': 'NOT', 'OP': 'OP', 'INC': 'INC'
}

GLOBAL_HIERARCHY_MAPPING = {
    'MOs_6b': 'CTX', 'MOs_6a': 'CTX', 'PVR_pd': 'HY', 'AOB_gl': 'CTX',
    'FL_mo': 'HB', 'PRNr': 'HB', 'PAS': 'HB', 'SSp_tr_2/3': 'CTX',
    'AON_1': 'CTX', 'PRNc': 'HB', 'ANcr1_mo': 'HB', 'PYR_mo': 'HB',
    'ANcr2_gr': 'HB', 'MEA_pd_c': 'AMY', 'MEA_pd_b': 'AMY', 'MEA_pd_a': 'AMY',
    'Gpe': 'STR', 'TEa_6a': 'CTX', 'SPA': 'TH', 'POST_3': 'HPF',
    'TEa_6b': 'CTX', 'PERI_6a': 'CTX', 'PERI_6b': 'CTX', 'AON_d': 'CTX',
    'AON_e': 'CTX', 'PV_po': 'HY', 'GR': 'HB', 'LHA': 'HY', 'AON_l': 'CTX',
    'AON_m': 'CTX', 'AUDv_6b': 'CTX', 'AUDv_6a': 'CTX', 'NPC': 'MB',
    'AOB_gr': 'CTX', 'LAV': 'HB', 'PSTN': 'HY', 'VISpl_1': 'CTX', 'DTN': 'HB',
    'SSp_m_2/3': 'CTX', 'PBl_ls': 'HB', 'PAG': 'MB', 'PBl_lv': 'HB',
    'SCs_op': 'MB', 'PTLp_6b': 'CTX', 'BST_rh': 'STR', 'PTLp_6a': 'CTX',
    'PBl_lc': 'HB', 'ORBl_2/3': 'CTX', 'PCG': 'HB', 'PBl_le': 'HB',
    'PBl_ld': 'HB', 'PVH_mpv': 'HY', 'VMH_dm': 'HY', 'MOp_2/3': 'CTX',
    'AIp_6a': 'CTX', 'AIp_6b': 'CTX', 'PVH_ap': 'HY', 'ZI': 'HY', 'AMB_v': 'HB',
    'DCO': 'HB', 'RSPv_5': 'CTX', 'RSPv_1': 'CTX', 'RSPv_2': 'CTX',
    'VISC_4': 'CTX', 'VISC_5': 'CTX', 'AMB_d': 'HB', 'MOB_mi': 'CTX',
    'NLOT_2': 'CTX', 'VISC_1': 'CTX', 'GRN': 'HB', 'CNspg': 'HB', 'IGL': 'TH',
    'ME': 'HY', 'NTB': 'HB', 'MA': 'STR', 'MB': 'MB', 'MM': 'HY', 'OT_1': 'CTX',
    'OT_2': 'CTX', 'OT_3': 'CTX', 'PBG': 'MB', 'VISC_2/3': 'CTX',
    'SUBv_m': 'HPF', 'MV': 'HB', 'MS': 'STR', 'NOT': 'MB', 'MY': 'HB',
    'INC': 'MB', 'FS': 'STR', 'NTS_m': 'HB', 'NTS_l': 'HB', 'VPM_pc': 'TH',
    'SCs_zo': 'MB', 'FC': 'HPF', 'SCM_ig-a': 'MB', 'SCM_ig-c': 'MB',
    'SCM_ig-b': 'MB', 'SOC_m': 'HB', 'SOC_l': 'HB', 'RSPv_2/3': 'CTX',
    'VISpm_2/3': 'CTX', 'PL_5': 'CTX', 'PL_6': 'CTX', 'PL_1': 'CTX',
    'PL_3': 'CTX', 'PL_2': 'CTX', 'CA2_sr': 'HPF', 'CA2_sp': 'HPF',
    'SUBv_sp': 'HPF', 'SUBv_sr': 'HPF', 'POST_1': 'HPF', 'Ep_v': 'CTX',
    'V': 'HB', 'VMH_vl': 'HY', 'CA2_so': 'HPF', 'FL_gr': 'HB', 'ILA_2/3': 'CTX',
    'PAR_1': 'HPF', 'PAR_3': 'HPF', 'PAR_2': 'HPF', 'PPT': 'MB', 'MARN': 'HB',
    'SI': 'STR', 'SH': 'STR', 'SO': 'HY', 'DP_2/3': 'CTX', 'VISpl_5': 'CTX',
    'SG': 'HB', 'SF': 'STR', 'AUDd_1': 'CTX', 'AUDd_5': 'CTX', 'AUDd_4': 'CTX',
    'SPF_p': 'TH', 'AIp_1': 'CTX', 'VPL_pc': 'TH', 'AIp_5': 'CTX',
    'COPY_gr': 'HB', 'BST_BAC': 'STR', 'LD': 'TH', 'VAL': 'TH', 'LA': 'AMY',
    'SSp_tr_1': 'CTX', 'SSp_tr_4': 'CTX', 'SSp_tr_5': 'CTX', 'LT': 'MB',
    'LP': 'TH', 'IAD': 'TH', 'VPM': 'TH', 'BST_if': 'STR', 'III': 'MB',
    'AId_6a': 'CTX', 'MOs_6': 'CTX', 'MOs_5': 'CTX', 'PVH_lp': 'HY',
    'LING_mo': 'HB', 'MOs_1': 'CTX', 'PRE_3': 'HPF', 'PRE_2': 'HPF',
    'PRE_1': 'HPF', 'LC': 'HB', 'FOTU_gr': 'HB', 'VISp_1': 'CTX',
    'POST_2': 'HPF', 'VISp_5': 'CTX', 'VISp_4': 'CTX', 'ORBm_3': 'CTX',
    'ORBm_2': 'CTX', 'ORBm_1': 'CTX', 'VISpl_4': 'CTX', 'ORBm_6': 'CTX',
    'ORBm_5': 'CTX', 'ENTm_3': 'CTX', 'ENTm_2': 'CTX', 'ENTm_1': 'CTX',
    'AHN_p': 'HY', 'ENTm_6': 'CTX', 'ENTm_5': 'CTX', 'ENTm_4': 'CTX',
    'LIN': 'HB', 'ANcr1_gr': 'HB', 'AHN_c': 'HY', 'MOs_2/3': 'CTX',
    'AHN_a': 'HY', 'LH': 'TH', 'CENT3_gr': 'HB', 'PVH_pv': 'HY', 'LM': 'HY',
    'AId_6': 'CTX', 'AId_5': 'CTX', 'AOB': 'CTX', 'RR': 'MB', 'AId_1': 'CTX',
    'SAG': 'MB', 'RE': 'TH', 'ENTm_2a': 'CTX', 'PRP': 'HB', 'RL': 'MB',
    'RM': 'HB', 'RN': 'MB', 'RO': 'HB', 'RH': 'TH', 'PM_v': 'HY', 'TM_d': 'HY',
    'ENTl_4/5': 'CTX', 'TEa_1': 'CTX', 'NOD_mo': 'HB', 'TTd_4': 'CTX',
    'MRN': 'MB', 'TTd_1': 'CTX', 'TTd_2': 'CTX', 'TTd_3': 'CTX', 'SUM_m': 'HY',
    'SUV': 'HB', 'MOB_gr': 'CTX', 'VII': 'HB', 'IPN': 'MB', 'ANCr2_mo': 'HB',
    'ORBvl_6b': 'CTX', 'SFO': 'HY', 'ORBvl_6a': 'CTX', 'APN': 'MB',
    'MOB_gl': 'CTX', 'SUT': 'HB', 'CUL4/5_mo': 'HB', 'BST_mg': 'STR',
    'PRC': 'TH', 'Scig_b': 'MB', 'ENTl_2/3': 'CTX', 'ORBl_6a': 'CTX',
    'ZI_A13': 'HY', 'ORBl_6b': 'CTX', 'IP': 'HB', 'STN': 'HY',
    'SSp_bfd_6b': 'CTX', 'SSp_bfd_6a': 'CTX', 'ACAv_6a': 'CTX',
    'VISal_2/3': 'CTX', 'ACAv_6b': 'CTX', 'PAA_2': 'CTX', 'PAA_3': 'CTX',
    'PAA_1': 'CTX', 'BST_dm': 'STR', 'ORBm_6a': 'CTX', 'EW': 'MB', 'PVT': 'TH',
    'POL': 'TH', 'FRP_1': 'CTX', 'PRM_gr': 'HB', 'IO': 'HB', 'SIM_gr': 'HB',
    'ORBm_2/3': 'CTX', 'Y': 'HB', 'ISN': 'HB', 'ECT_1': 'CTX', 'ECT_5': 'CTX',
    'IC_c': 'MB', 'IC_e': 'MB', 'IC_d': 'MB', 'AM_v': 'TH', 'PGRN_l': 'HB',
    'ECU': 'HB', 'CENT2_mo': 'HB', 'PGRN_d': 'HB', 'IF': 'MB', 'AM_d': 'TH',
    'VTA': 'MB', 'SSp_ul_1': 'CTX', 'B': 'HB', 'CLI': 'MB', 'SSp_ul_5': 'CTX',
    'SSp_ul_4': 'CTX', 'CS_l': 'HB', 'COApl_1': 'CTX', 'COApl_2': 'CTX',
    'VTN': 'MB', 'SSp_ll_2/3': 'CTX', 'PERI_2/3': 'CTX', 'BST_se': 'STR',
    'ZI_FF': 'HY', 'BST_ju': 'STR', 'KF': 'HB', 'MEA_av': 'AMY',
    'CA3_slm': 'HPF', 'VISpm_1': 'CTX', 'MOB_ipl': 'CTX', 'VISpl_2/3': 'CTX',
    'ORBl_1': 'CTX', 'ORBl_6': 'CTX', 'VISpm_4': 'CTX', 'CA3_slu': 'HPF',
    'CA1_slm': 'HPF', 'LG_d': 'TH', 'SSs_6a': 'CTX', 'CA2_slm': 'HPF',
    'MEA_ad': 'AMY', 'DN': 'HB', 'NTS_ge': 'HB', 'AAA': 'AMY', 'TR_3': 'CTX',
    'ILA_5': 'CTX', 'TR_1': 'CTX', 'SSs_2/3': 'CTX', 'ILA_1': 'CTX',
    'ILA_2': 'CTX', 'ILA_3': 'CTX', 'CUL_mo': 'HB', 'RSPagl_2/3': 'CTX',
    'ENTl_2': 'CTX', 'ENTl_3': 'CTX', 'COApl_3': 'CTX', 'ENTl_1': 'CTX',
    'ENTl_6': 'CTX', 'ENTl_4': 'CTX', 'ENTl_5': 'CTX', 'VPL': 'TH',
    'DP_6a': 'CTX', 'TTv_2': 'CTX', 'TTv_3': 'CTX', 'TTv_1': 'CTX', 'POR': 'HB',
    'DG_mo': 'HPF', 'RPA': 'HB', 'COAa_2': 'CTX', 'COAa_1': 'CTX',
    'SSp_ll_1': 'CTX', 'VISal_1': 'CTX', 'LING_gr': 'HB', 'SSp_ll_4': 'CTX',
    'SSp_ll_5': 'CTX', 'VISal_5': 'CTX', 'VISal_4': 'CTX', 'AON_pv': 'CTX',
    'SSp_2/3': 'CTX', 'SN_c': 'MB', 'CLA': 'CTX', 'RSPagl_1': 'CTX',
    'SLD': 'HB', 'AUDPo_1': 'CTX', 'BST_AL': 'STR', 'AUDPo_5': 'CTX',
    'AUDPo_4': 'CTX', 'LRN_p': 'HB', 'RSPagl_5': 'CTX', 'PVH_f': 'HY',
    'VMH_a': 'HY', 'VMH_c': 'HY', 'PVH_a': 'HY', 'LRN_m': 'HB', 'PVH_mpd': 'HY',
    'FRP_2/3': 'CTX', 'SCm_dw': 'MB', 'Gpi': 'STR', 'PERI_1': 'CTX',
    'ILA_6b': 'CTX', 'ILA_6a': 'CTX', 'PERI_5': 'CTX', 'SCm_dg': 'MB',
    'AUDp_2/3': 'CTX', 'VISl_5': 'CTX', 'VISl_4': 'CTX', 'VISl_1': 'CTX',
    'ACVII': 'HB', 'SSp_bfd_5': 'CTX', 'SSp_bfd_4': 'CTX', 'SSp_bfd_1': 'CTX',
    'IAM': 'TH', 'XII': 'HB', 'LDT': 'HB', 'X': 'HB', 'ACAd_2/3': 'CTX',
    'VISC_6a': 'CTX', 'SUM_l': 'HY', 'VISC_6b': 'CTX', 'AId_6b': 'CTX',
    'VISp_6a': 'CTX', 'VISp_6b': 'CTX', 'DG_sg': 'HPF', 'NTS_co': 'HB',
    'CUL4/5_gr': 'HB', 'BMA_p': 'AMY', 'NTS_ce': 'HB', 'AId_2/3': 'CTX',
    'SSp_n_1': 'CTX', 'SSp_n_5': 'CTX', 'SSp_n_4': 'CTX', 'DMX': 'HB',
    'BMA_a': 'AMY', 'PR': 'TH', 'PS': 'HY', 'PP': 'TH', 'AON': 'CTX',
    'PT': 'TH', 'TEa_5': 'CTX', 'PA': 'AMY', 'PF': 'TH', 'PG': 'HB',
    'SIM_mo': 'HB', 'LS_c': 'STR', 'VISpm_5': 'CTX', 'PH': 'HY', 'PO': 'TH',
    'RT': 'TH', 'AUDpo_6b': 'CTX', 'SSp_ll_6b': 'CTX', 'SSp_ll_6a': 'CTX',
    'ORBl_5': 'CTX', 'DEC_mo': 'HB', 'PL_2/3': 'CTX', 'LS_r': 'STR',
    'ORBvl_6': 'CTX', 'ORBvl_5': 'CTX', 'LS_v': 'STR', 'ORBvl_1': 'CTX',
    'PFL_mo': 'HB', 'BLA_a': 'AMY', 'AUDPo_2/3': 'CTX', 'BLA_p': 'AMY',
    'SSs_6b': 'CTX', 'ENTmv_3': 'CTX', 'PSV': 'HB', 'PST': 'HY',
    'NLOT_1': 'CTX', 'COApm_1': 'CTX', 'COApm_2': 'CTX', 'COApm_3': 'CTX',
    'BST_pr': 'STR', 'NLOT_3': 'CTX', 'CA3_sp': 'HPF', 'CA3_sr': 'HPF',
    'LG_v': 'TH', 'CA3_so': 'HPF', 'MEA_pv': 'AMY', 'PBm_m': 'HB',
    'VISam_1': 'CTX', 'VISam_4': 'CTX', 'VISam_5': 'CTX', 'PIR_1': 'CTX',
    'ENTmv_1': 'CTX', 'PIR_3': 'CTX', 'ENTl_6b': 'CTX', 'AIv_6b': 'CTX',
    'AIv_6a': 'CTX', 'AUDv_2/3': 'CTX', 'TR_2': 'CTX', 'TEa_2/3': 'CTX',
    'MD_c': 'TH', 'CM': 'TH', 'CL': 'TH', 'NDB': 'STR', 'ACAv_2/3': 'CTX',
    'DP_1': 'CTX', 'PCN': 'TH', 'CEA_l': 'AMY', 'CP': 'STR', 'CU': 'HB',
    'VLPO': 'HY', 'SPVO_mdmv': 'HB', 'PFL_gr': 'HB', 'RSPv_6a': 'CTX',
    'MD_I': 'TH', 'MPN_m': 'HY', 'MPN_l': 'HY', 'RSPd_2/3': 'CTX', 'IMD': 'TH',
    'SPVO_cdm': 'HB', 'RSPd_6a': 'CTX', 'RSPd_6b': 'CTX', 'MPN_c': 'HY',
    'SSp_tr_6a': 'CTX', 'SPVO_mdmd': 'HB', 'SSp_tr_6b': 'CTX', 'PRM_mo': 'HB',
    'PONS': 'HB', 'MH': 'TH', 'SSp-un_6b': 'CTX', 'SN_r': 'MB',
    'SSp-un_6a': 'CTX', 'RCH': 'HY', 'ORBvl_2/3': 'CTX', 'SCs_sg': 'MB',
    'MOB_opl': 'CTX', 'DR': 'MB', 'PPN': 'MB', 'BST_OV': 'STR',
    'ENTm_2b': 'CTX', 'TEa_4': 'CTX', 'ACAv_5': 'CTX', 'ACAv_1': 'CTX',
    'CENT2_gr': 'HB', 'PPY': 'HB', 'BLA_v': 'AMY', 'VISal_6b': 'CTX',
    'VISal_6a': 'CTX', 'VI': 'HB', 'PTLp_2/3': 'CTX', 'IV': 'MB', 'IRN': 'HB',
    'MOB': 'CTX', 'IA': 'AMY', 'AIv_2/3': 'CTX', 'IG': 'HPF', 'GU_6a': 'CTX',
    'LPO': 'HY', 'SSp-un_5': 'CTX', 'SSp-un_4': 'CTX', 'A13': 'HY',
    'SSp-un_1': 'CTX', 'UVU_gr': 'HB', 'TM_v': 'HY', 'CENT3_mo': 'HB',
    'BST_v': 'STR', 'ARH': 'HY', 'ACAd_6b': 'CTX', 'ACAd_6a': 'CTX',
    'VISp_2/3': 'CTX', 'BA': 'AMY', 'RSPv_6b': 'CTX', 'PARN': 'HB',
    'MOp_6b': 'CTX', 'MOp_6a': 'CTX', 'GU_4': 'CTX', 'SMT': 'TH',
    'ECT_2/3': 'CTX', 'SSp_m_4': 'CTX', 'SSp_m_5': 'CTX', 'SSp_m_1': 'CTX',
    'SBPV': 'HY', 'DG_po': 'HPF', 'CEA_c': 'AMY', 'CEA_m': 'AMY',
    'VISpm_6a': 'CTX', 'VISpm_6b': 'CTX', 'ENTl_2a': 'CTX', 'ENTl_2b': 'CTX',
    'VISam_6a': 'CTX', 'VISpl_6b': 'CTX', 'VISpl_6a': 'CTX', 'VISam_6b': 'CTX',
    'BST_fu': 'STR', 'DMH_v': 'HY', 'DMH_p': 'HY', 'MEPO': 'HY',
    'SSp_n_6b': 'CTX', 'DMH_a': 'HY', 'SSp_n_6a': 'CTX', 'AUDPo_6a': 'CTX',
    'SSp_1': 'CTX', 'SSp_4': 'CTX', 'SSp_5': 'CTX', 'ECT_6b': 'CTX',
    'ECT_6a': 'CTX', 'OV': 'HY', 'OP': 'MB', 'NLL_h': 'HB', 'HY': 'HY',
    'MDRN_d': 'HB', 'ACAd_1': 'CTX', 'ACAd_5': 'CTX', 'ACAd_6': 'CTX',
    'SPF_m': 'TH', 'AOB_mi': 'CTX', 'NOD_gr': 'HB', 'PYR_gr': 'HB',
    'MDRN_v': 'HB', 'NLL_v': 'HB', 'VISl_2/3': 'CTX', 'PV_a': 'HY',
    'SPV_i': 'HB', 'AUDd_6a': 'CTX', 'AUDd_6b': 'CTX', 'PV_i': 'HY',
    'AMB': 'HB', 'SPV_c': 'HB', 'PV_p': 'HY', 'VM': 'TH', 'FN': 'HB',
    'ICB': 'HB', 'PTLp_1': 'CTX', 'PTLp_5': 'CTX', 'PTLp_4': 'CTX',
    'MM_me': 'HY', 'TRN': 'HB', 'CS_m': 'HB', 'MG_v': 'TH', 'sAMY': 'AMY',
    'MG_m': 'TH', 'TRS': 'STR', 'VCO': 'HB', 'ACB': 'STR', 'MG_d': 'TH',
    'AVPV': 'HY', 'EP_d': 'CTX', 'RPO': 'HB', 'MPN': 'HY', 'CA1_sr': 'HPF',
    'CA1_sp': 'HPF', 'AVP': 'HY', 'ENTl_6a': 'CTX', 'MPT': 'MB',
    'CA1_so': 'HPF', 'ENTmv_2': 'CTX', 'BST_tr': 'STR', 'PL_6a': 'CTX',
    'PL_6b': 'CTX', 'PIR_2': 'CTX', 'RSPagl_6b': 'CTX', 'RSPagl_6a': 'CTX',
    'FOTU_mo': 'HB', 'PVH_mm': 'HY', 'GU_2/3': 'CTX', 'PM_d': 'HY',
    'SSp_6a': 'CTX', 'BST_AM': 'STR', 'SSp_6b': 'CTX', 'NI': 'HB', 'NB': 'MB',
    'NC': 'HY', 'ND': 'STR', 'AUDp_6a': 'CTX', 'AUDp_6b': 'CTX', 'CNlam': 'HB',
    'NR': 'HB', 'SLC': 'HB', 'DP_5': 'CTX', 'SSp-un_2/3': 'CTX', 'ADP': 'HY',
    'SSp_ul_6b': 'CTX', 'SSp_ul_6a': 'CTX', 'DEC_gr': 'HB', 'NLL_d': 'HB',
    'PBm_me': 'HB', 'AUDp_5': 'CTX', 'AUDp_4': 'CTX', 'COPY_mo': 'HB',
    'AUDp_1': 'CTX', 'PVH_pmm': 'HY', 'PVH_pml': 'HY', 'AUDv_5': 'CTX',
    'AUDv_4': 'CTX', 'AIp_2/3': 'CTX', 'ADH_p': 'HY', 'AUDv_1': 'CTX',
    'MEV': 'MB', 'UVU_mo': 'HB', 'AIv_1': 'CTX', 'SPVO_vl': 'HB',
    'AIv_5': 'CTX', 'RSPd_1': 'CTX', 'ENTmv_5/6': 'CTX', 'RSPd_5': 'CTX',
    'SPVO_rdm': 'HB', 'SPIV': 'HB', 'AUDd_2/3': 'CTX', 'SUBd_m': 'HPF',
    'SCm_ig': 'MB', 'MPO': 'HY', 'SSp_ul_2/3': 'CTX', 'GU_6b': 'CTX',
    'GU_1': 'CTX', 'SSp_bfd_2/3': 'CTX', 'TU': 'HY', 'GU_5': 'CTX',
    'SSp_m_6b': 'CTX', 'SSp_m_6a': 'CTX', 'SCm_iw': 'MB', 'SSp_n_2/3': 'CTX',
    'SGN': 'TH', 'BST_d': 'STR', 'CUN': 'MB', 'MD_m': 'TH', 'AD': 'TH',
    'VISl_6a': 'CTX', 'VISl_6b': 'CTX', 'AP': 'HB', 'PVH_dp': 'HY', 'AT': 'MB',
    'AV': 'TH', 'SSs_5': 'CTX', 'SSs_4': 'CTX', 'SSs_1': 'CTX', 'SCH': 'HY',
    'MOp_1': 'CTX', 'MOp_5': 'CTX', 'MOp_6': 'CTX', 'SubG': 'TH',
    'VISam_2/3': 'CTX', 'SUBd_sr': 'HPF', 'SUBd_sp': 'HPF'
}

GLOBAL_COARSE_MAPPING = \
    { k: v for d in [CTX_COARSE_MAPPING, HY_COARSE_MAPPING, AMY_COARSE_MAPPING,
                     HPF_COARSE_MAPPING, STR_COARSE_MAPPING, MB_COARSE_MAPPING]
      for k, v in d.items()}
for k in TH_ROIS:
    GLOBAL_COARSE_MAPPING[k] = k
for k in HB_ROIS:
    GLOBAL_COARSE_MAPPING[k] = k

# needs expansion
ROI_GROUPS = {
    'CTX_COARSE': set([roi_name for roi_name in CTX_COARSE_MAPPING]),
    'CTX_DS': set([roi_name for roi_name in CTX_DS_MAPPING]),
    'OLFACTORY': set([roi_name for roi_name in OLFACTORY_AREA_COARSE_MAPPING]),
    'SENSORY': set([roi_name for roi_name in SENSORY_AREA_COARSE_MAPPING]),
    'TH': TH_ROIS,
    'HY': set([roi_name for roi_name in HY_COARSE_MAPPING]),
    'AMY': set([roi_name for roi_name in AMY_COARSE_MAPPING]),
    'HPF': set([roi_name for roi_name in HPF_COARSE_MAPPING]),
    'STR': set([roi_name for roi_name in STR_COARSE_MAPPING]),
    'MB': set([roi_name for roi_name in MB_COARSE_MAPPING]),
    'HB': HB_ROIS,
    'GLOBAL_COARSE': set([roi_name for roi_name in GLOBAL_COARSE_MAPPING]),
    'GLOBAL_HIERARCHY': set([roi_name for roi_name in GLOBAL_HIERARCHY_MAPPING])
}

ROI_MAPPINGS = {
    'CTX_COARSE': CTX_COARSE_MAPPING,
    'CTX_DS': CTX_DS_MAPPING,
    'OLFACTORY_COARSE': OLFACTORY_AREA_COARSE_MAPPING,
    'SENSORY_COARSE': SENSORY_AREA_COARSE_MAPPING,
    'HY_COARSE': HY_COARSE_MAPPING,
    'AMY_COARSE': AMY_COARSE_MAPPING,
    'HPF_COARSE': HPF_COARSE_MAPPING,
    'STR_COARSE': STR_COARSE_MAPPING,
    'MB_COARSE': MB_COARSE_MAPPING,
    'GLOBAL_COARSE': GLOBAL_COARSE_MAPPING,
    'GLOBAL_HIERARCHY': GLOBAL_HIERARCHY_MAPPING
}

"""
# roi_hierachy.csv
# roi, index, group, roi_coarse, roi_ds
# roi: name of region same as in translate colors
# index: rgb index of a roi
# roi_coarse: coarser region, evolving, collapse cortex layers
#             (ILA2, ILA3 -> ILA, SCm_d, SCm_a -> SCm)
# roi_ds: cortex layers collapsed into deep vs superficial
d = {}
with open('/ifs/loni/faculty/dong/mcp/muye/manuscripts/dp_ila_ttd/roi_hierachy.csv', 'r') as f:
    for l in f:
        tokens = l.strip().split(',')
        roi, index, group, roi_coarse, roi_ds = tokens
        if group == 'BORDER' or group == 'VENTRICLE' or group == 'WHITE_MATTER':
            continue
        d[roi] = group
print(d)
"""